package com.aref.jarvis;
import android.content.*;import android.security.keystore.*;import android.util.Base64;import java.nio.charset.StandardCharsets;import java.security.KeyStore;import javax.crypto.*;import javax.crypto.spec.GCMParameterSpec;
public class Store{
 private static final String PREF="jarvis_secure",ALIAS="JARVIS_AES";private final SharedPreferences p;
 public boolean away;public String key="",rules="",log="";
 public Store(Context c){p=c.getSharedPreferences(PREF,0);away=p.getBoolean("away",false);rules=p.getString("rules","همیشه فارسی، طبیعی، کوتاه و محترمانه پاسخ بده.");log=p.getString("log","");String e=p.getString("keys_secure","");if(!e.isEmpty())key=decrypt(e);else{String legacy=p.getString("keys","");if(!legacy.isEmpty()){key=legacy;save();}}}
 public synchronized void save(){SharedPreferences.Editor e=p.edit().putBoolean("away",away).putString("rules",rules).putString("log",trim(log));if(key!=null&&!key.isEmpty())e.putString("keys_secure",encrypt(key));else e.remove("keys_secure");e.remove("keys").apply();}
 public synchronized String nextKey(){String[] a=key==null?new String[0]:key.split("\\|");java.util.ArrayList<String> v=new java.util.ArrayList<>();for(String x:a)if(!x.trim().isEmpty())v.add(x.trim());if(v.isEmpty())return "";int i=p.getInt("ki",0)%v.size();p.edit().putInt("ki",(i+1)%v.size()).apply();return v.get(i);}
 public synchronized void addLog(String x){log=trim((log==null?"":log)+"\n"+x);save();}
 public synchronized boolean seen(String n,String b){String k="seen_"+Integer.toHexString((n+"|"+b).hashCode());if(p.getBoolean(k,false))return true;p.edit().putBoolean(k,true).apply();return false;}
 public synchronized boolean canReply(String n){return System.currentTimeMillis()-p.getLong("last_"+safe(n),0)>=60000;}
 public synchronized void markReply(String n){p.edit().putLong("last_"+safe(n),System.currentTimeMillis()).apply();}
 private String safe(String s){return s==null?"unknown":s.replaceAll("[^0-9A-Za-z_]","_");}private String trim(String s){return s==null?"":s.length()>16000?s.substring(s.length()-16000):s;}
 private SecretKey secret(){try{KeyStore k=KeyStore.getInstance("AndroidKeyStore");k.load(null);if(!k.containsAlias(ALIAS)){KeyGenerator g=KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES,"AndroidKeyStore");g.init(new KeyGenParameterSpec.Builder(ALIAS,KeyProperties.PURPOSE_ENCRYPT|KeyProperties.PURPOSE_DECRYPT).setBlockModes(KeyProperties.BLOCK_MODE_GCM).setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE).build());g.generateKey();}return ((KeyStore.SecretKeyEntry)k.getEntry(ALIAS,null)).getSecretKey();}catch(Exception e){return null;}}
 private String encrypt(String s){try{SecretKey k=secret();if(k==null)return "";Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,k);return Base64.encodeToString(c.getIV(),2)+"."+Base64.encodeToString(c.doFinal(s.getBytes(StandardCharsets.UTF_8)),2);}catch(Exception e){return "";}}
 private String decrypt(String s){try{String[] a=s.split("\\.",2);if(a.length!=2)return "";SecretKey k=secret();if(k==null)return "";Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.DECRYPT_MODE,k,new GCMParameterSpec(128,Base64.decode(a[0],2)));return new String(c.doFinal(Base64.decode(a[1],2)),StandardCharsets.UTF_8);}catch(Exception e){return "";}}
}